### ISSUE TITLE
Location user-friendliness

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#11]
When entering location data, it would be nice to specify that the address must be added first, then the location can be added.  In fact, it might be nice to allow the user to start to enter the location, but then tell user “this location does not have an address yet.  Would you like to set one up?” And then display the address view.

**Comment by evillaflor** [comment]
Added a link to the add location page that links to the add address page so that creating a new location with a new address, that is not in the drop down menu, is more intuitive.
