### ISSUE TITLE
Software uniqueness

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#12]
Consider what makes software unique - is the software table actually a table of licenses?  If so, the license key should be unique.  If not, the composite key of software name and version should be unique.  Duplicates shouldn't be allowed, right?

**Comment by mrigsbee** [comment]
Now if you try to add a software object that has the same license key as a software object already in the database, it will not be added and an error message should display.

**Comment by mrigsbee** [comment]
Found another bug when adding software without matching license key. In progress currently.
