### ISSUE TITLE
Software advanced search - cost range

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#13]
The cost range doesn't seem to work for software search - errors are returned even when there should be records returned.  In addition, you could consider enforcing that a lower number is entered on the left and a higher number is written on the right.  (Or you could just handle that code-wise if ranges are entered backwards.)

**Comment by seamuslowry** [comment]
Could not reproduce error from cost range.  Modified code to use numbers as min and max based on value rather than order of entry

**Comment by jya17** [comment]
Error returned when single cost field is entered.

**Comment by seamuslowry** [comment]
single cost field now handled by duplicating value on backend
