### ISSUE TITLE
New user - possibly not a problem?

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#16]
Adding a new user doesn't show up in events.  Is that an issue?

The phone number entry for users is not restricted to any kind of format or number of digits.  This might not be a problem.  Sometimes users could have extensions.  International numbers have parentheses in them, etc.  Just documenting that, I think, so that I won't try to keep fixing that.  We are OK with users submitting phone numbers with various formats?

**Comment by woosanghun** [comment]
I'm OK with leaving it open.  If we try to be too restrictive, we may accidentally exclude formats that would be valid in foreign countries.   The contact information is for their informational use.

**Comment by woosanghun** [comment]
On the comment for new users, it would be good to have an audit trail of that.

**Comment by evillaflor** [comment]
Adding a new user is added as a System Event and can be seen from both the Events list page as well as in the Events table at the bottom of the User info page. The message associated with the creation of a new User was modified to explicitly state that a new User with the given username was created.
