### ISSUE TITLE
Handling new user email or password fail

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#18]
If an admin is adding a new user, would it be OK to give the admin a notification that an email has been sent?  Or there could be text on the page telling the admin that this occurs when adding a new user.  That way a new admin would not duplicate that effort by emailing the person manually.

If for some reason, a user enters a bad email address, can the administrator be notified that the email was not delivered?

If a user tries to log in before having a password established (the user didn't wait for the email with the password), the website gives a 500 error because there is no password to check against.  Maybe handle this error more elegantly, even if this would occur rarely.

**Comment by evillaflor** [comment]
Added more meaningful success messages for adding/updating/deleting users. The messages include the username and the action that occurred.

Still trying to handle invalid e-mail addresses and the 500 error mentioned above.

**Comment by evillaflor** [comment]
500 error could not be re-created after several attempts

**Comment by chrismhess** [comment]
Furthermore there is no way to handle whether or not a valid email was put in by the user. We haven't figured out a way to handle this other than just hoping the user realizes their mistake when they don't have the correct email put in.

**Comment by seamuslowry** [comment]
500 error replicated and fixed
