### ISSUE TITLE
Can new hardware come with software preinstalled?

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#8]
Consider including software as an option to list for hardware as it is being entered for the first time.

**Comment by mrigsbee** [comment]
The purpose of the software list is to track software specifically purchased separately. The software that comes preinstalled on a computer was included with the cost of the computer. Essentially, the software preinstalled is already being tracked by tracking the computer. So, software that isn't necessarily linked to a hardware object would be tracked by the software list.

Some examples would be a copy of Microsoft Office bought from Microsoft or a custom software made by the company.

Hope that helps!
